### ISSUE TITLE
how do I install this extension to VSCode?

### ISSUE THREAD

**Issue by bacongobbler** [technosophos/vscode-helm#1]
I'm interested in testing this out, but I can't find it in the marketplace!

<img width="1680" alt="screen shot 2017-05-18 at 11 43 50 am" src="https://cloud.githubusercontent.com/assets/1360539/26218317/6545565c-3bbf-11e7-86c1-2d36bea68af9.png">

How have you got this installed locally? Perhaps I can PR some documentation on how others can install this plugin.

**Comment by technosophos** [comment]
I added this to VSCE today. So as of right now, you can add it the way you describe above.
