### ISSUE TITLE
Preview Template long loading and nothing showed

### ISSUE THREAD

**Issue by tuannvm** [technosophos/vscode-helm#6]
Running `Helm preview template`, successfully ran for the first time.
Open second file, rendering template --> It loads forever.

**Comment by jinseo-jang** [comment]
The same symptom happened to [me.](url) 
<img width="684" alt="2017-10-19 10 27 45" src="https://user-images.githubusercontent.com/31303240/31784893-32fae7d0-b4b8-11e7-95ff-1b1466377d6d.png">

Is there any solution for this??
Thanks in advance

**Comment by tuannvm** [comment]
I notice that if I accidentally open a new tab in the `right pane` (same pane with preview tab), then it will happen.
